-- Two-factor authentication (TOTP) for CRM users.
--
-- Adds a per-user TOTP secret and an enabled flag. The secret is a Base32 string
-- (RFC 4648) generated by the API (server/totp.js); it is never exposed through
-- the generic read path (server/index.js redacts crm_user.totp_secret alongside
-- password_hash). The login endpoint requires a valid code whenever totp_enabled
-- is true.
--
-- Idempotent — the API also ensures these columns on boot (ensureAuthSchema).

ALTER TABLE crm_user ADD COLUMN IF NOT EXISTS totp_secret  text;
ALTER TABLE crm_user ADD COLUMN IF NOT EXISTS totp_enabled boolean NOT NULL DEFAULT false;
