GRANT EXECUTE ON FUNCTION public.crm_user_has_access(text, uuid, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.crm_user_has_privilege(text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_system_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_view_owner(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_has_view_share(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_check_product_access(uuid, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_evaluate_data_policies(text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_evaluate_data_policies(text, jsonb, text, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_bu_subtree(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_users_in_bu(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_users_in_bu_subtree(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_get_user_display_map(uuid[]) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_table_columns(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.increment_workflow_run_count(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.advance_process_stage(uuid, uuid, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_or_create_process_flow_instance(uuid, uuid, uuid, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_process_flow_instance(uuid, text, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.soft_delete_process_flow(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.soft_delete_qualification_rule(uuid) TO authenticated;